### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by Shmookoff** [camalot/obs-lastfm#1]
I know, i am stupid, but can someone help me? Why does it tell me that "Page Not Found"? I did everything according to the instructions
![image](https://user-images.githubusercontent.com/23117885/57688611-501fbb80-7657-11e9-8e6a-e6787e40dd8e.png)

**Comment by snowman03** [comment]
Use https:// heroku url /overlay/ lastfm username

Like https://lastfm-obs.herokuapp.com/overlay/Shmykoff

**Comment by SunbroJedi** [comment]
I have the same problem, and even if I do that it still doesn't work
![image](https://user-images.githubusercontent.com/55336959/126085862-853d7c3b-fda9-4299-80bd-9c03310941e4.png)
